### ISSUE TITLE
Is there any corresponding literature？

### ISSUE THREAD

**Issue by gardenia1229** [bryanlimy/mri-super-resolution#2]
Is there any corresponding literature？

**Comment by bryanlimy** [comment]
Hi @gardenia1229, we will be submitting (and releasing) this work very soon. The code in this repository is not the most up to date.

**Comment by gardenia1229** [comment]
Look forward to your latest achievements.

在2021-10-14 ***@***.***写道：

Hi @gardenia1229, we will be submitting the latest of the work very soon. The code in this repository is not up to date.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
